server:
  port: 2000

spring:
  application:
    name: crowd-mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.71.104:3306/project_crowd?serverTimezone=UTC
    username: root
    password: zxcvbnm00
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml

eureka:
  client:
    service-url:
      defaultZone: http://192.168.71.104:1000/eureka

logging:
  level:
    com.wf.crowd.mapper: debug
    com.wf.crowd: debug
