server:
  port: 80
spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  application:
    name: crowd-zuul
  redis:
    host: 192.168.71.100
    password: 111111
  session:
      store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
#  host:
#    connect-timeout-millis: 60000
#    socket-timeout-millis: 60000
  ignored-services: "*"
  sensitive-headers: "*"  # 在Zuul向其他微服务重定向时保持原本头信息（请求头、响应头）
  routes:
    crowd-portal:
      service-id: crowd-auth
      path: /**
    crowd-project:
      service-id: crowd-project
      path: /project/**
  add-host-header: true
ribbon:
  ConnectTimeout: 20000 # 连接超时时间（ms）
  ReadTimeout: 20000 # 通信超时时间（ms）
  OkToRertryOnAllOperations: ture # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 #同一个服务不同实例的重试次数
  MaxAutoRetries: 1 #同一实例的重试次数
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 20000 #熔断超时时长 20000ms

