server:
  port: 8000

spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  application:
    name: crowd-pay
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  redis:
    host: 192.168.71.104
    password: 111111
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://192.168.71.104:1000/eureka

ali:
  pay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlpfMKmHsrN9uahLk7t1yqDUFSd6W5hwoqRmZvkCBi1ACaTfmlaUC6wK+4+Z6McdaSa/g8HhqCNB0XoK06aH2lhV/zAN4k2W14y0cad0Ph6ZuMiNE9jgmNgXYCgOvQQFfg9pki7vfpPkN579WYVKc0epYnqzEWCQobGk0zqbMjwPqPm3Xo9BAHRdQ9oIqp3yCnZEmq9QBqkvpDXWD9pY8vrYBIXAVJwBcygAciu4cP5g0fSRSAvIUW9nIm+IREHhtd1xVCX6Bk7j9aeT2d7AFglLHiLFeYG5rtR9xtd7akd0trx/ZuOAAQosMq3GpwhX3KqOuCL7obA4cmeMQLtklFQIDAQAB

    app-id: 9021000125623120
    charset: utf-8
    gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    merchant-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDLL20IJDnH6xPID/cfN8HIlGiBnpCtabXFZHSJJxyLkFf75WwXNSMqu22YK4xooSiKXLyDkoSINi7qRJb9zekPS1L8JtUh8cBDhchDGPTcXzGs4WwNav6Ggm9nZfkO+dcy7yJrQnei2e9JIKbTbtlT/9JBlVFV75YW+2VQ7wp4RXn9WERwhuJfW510yYaJOrhSPpzNr36zaBuPrhRQqUHHvB3iMys+io7B+W+jHIUwPVWMw13rsJ6eQUyo9kyYLYS7gSEK4L6haswmHTHvMiSr6voYPicetzLlz5WVfvHfGMHRdR9iG0/IowRYpOYPdd49xJ1GdeuGC8fseBLTx3ApAgMBAAECggEAa5vZfedZprSsjFdQRPtNqUJYOtXUv9LtjvZN9dl997hhsKnn3j6pOld7ioz91ugLRYQp3vD5Of6gSDg9U3v7Q7tb3uleFZUog1pWHpsYC6Jq96mHhW+2D10DTVqnVjQhsfsOWoogPGJ5pVwinnXlqeQh4dQH+KBj+BX6qat/+wO3HME1Ztuew3Z+3POM/u2vWe52whNsLy/Bhqrhb+ROjLU1rHnLFaMXd0YrtrMMeUIYIAhWtq8/x6VS3upd4jdwGTk5MDQnevAd5XTqMrfoU5dhulKCXs6pKpmeCt0FxCGyPhA3H3KRcQQJoD2xLUTU5ku2EHzNdpm7FI7UsSpRgQKBgQDpUqbdxyw53MQdtsGSYvaxiTxmJB8XJ7ZoZwTdf1LblphaR51WUejYFFNG5kYIUbT1tf1lhMRzM5q7pFB1t/0IMrbcMISNJuH8xlcLZGZFbgJBtXxKaenOY7o2003VHkzbxEN6uV0Txyv3+xDBGHsWqE4umamM9ru0PVF7sjlKUQKBgQDe7uo8fqROdfDSlPQIVyGpVsx4Qc18wsSsCcqDpMxPTiocleQVMxjST+DVCkp154i9heOT8E7rDs0qpntOQqqJJEmmahQmkccmYUPqI34pjCMNNRueQTB90b3cdwMEepWrn61xALyERma8cP8O4eowzacjYD2QLhBgSP3petJ6WQKBgQCDyIMnUI/SPrcmcUrz+6GKtRDAQDavRWbpoQZGdNu/21dB5qEfWDRDl3dR3E5B9KRZA+mTpWGwD72drjkjxD/OmZZe16iGcSfDNeOEM7jwDiqIIpGJFjlQsVNEFCUp8mtG1ZunfXrs6NoUvmHALquXKIjAGVqCm/l43Alh7FAfgQKBgAGFQaW9+2LpnQXirDNuXLVp+SUM1dj2/x5pRq9VLWuRDep5/z9BxPaSQudRFabuOFmKkz3MEs25oR6cWhTzkXQ0AiiXaqHEtsYFPdBYA6FG6mpJpXGT4j/JcXESgrvCFklAYo91wNNqI4M/hg3U7qL8lBpCqsjT95qghNLV2p+pAoGAKjtTyV3SWZ83bNkUg7k1Z1sqwpxf55RGgBlwOU1vZisOYOet/ZXFRRBjS3IK2EACNki0fntAp+UOC6R+tfXRWJGEfa+zw5H2ic+nL3WBfRmuth4W8TpT/U/cFEj0V+M/H8KAYg0nRhI//qDdkPaO3UYW+Pa91CXiRDze+OPnJhE=

    notify-url: http://2a398c.natappfree.cc/pay/notify
    return-url: http://192.168.71.104/pay/return
    return-url: http://192.168.71.104/pay/return
    sign-type: RSA2

