server:
  port: 5000

spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  application:
    name: crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: true  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  redis:
    host: 192.168.71.104
    password: 111111
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://192.168.71.104:1000/eureka
aliyun:
  oss:
    access-key-id: LTAI5tMFS3JsHYJ2LggKFavs
    access-key-secret: PGurIsbQILpi5KqMevRHy4jydTbmZK
    bucket-domain: http://wf-crowd.oss-cn-chengdu.aliyuncs.com
    bucket-name: wf-crowd
    end-point: http://oss-cn-chengdu.aliyuncs.com

