server:
  port: 4000

spring:
  application:
    name: crowd-auth
  redis:
    host: 192.168.71.104
    password: 111111
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: true  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  mail:
    host: smtp.qq.com
    username: 1332538873@qq.com
    password: nnspnseucdlmgffh
    default-encoding: utf-8


eureka:
  client:
    service-url:
      defaultZone: http://192.168.71.104:1000/eureka/