server:
  port: 3000

spring:
  application:
    name: crowd-redis
  redis:
    host: 192.168.71.100
    port: 6379
    password: 111111

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1000/eureka
