server:
  port: 3000

spring:
  application:
    name: crowd-redis
  redis:
    host: 192.168.71.104
    port: 6379
    password: 111111

eureka:
  client:
    service-url:
      defaultZone: http://192.168.71.104:1000/eureka
